bootstrap: add exception handling.
Catch autoreconf errors and set the scripts exit status to that of autoreconf.

Signed-off-by: Clement Chauplannaz <chauplac@gmail.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -2,5 +2,12 @@
 
 printf "Running autoreconf...\n"
 autoreconf -f -i
+rc=$?
 
-printf "Done. You may now run:\n    ./configure\n"
+if test $rc = 0; then
+	printf "Done. You may now run:\n    ./configure\n"
+else
+	printf "Failed! :-(\n"
+fi
+
+exit $rc
